<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useRoute, useRouter, RouterLink } from 'vue-router'
import { useHead } from '@unhead/vue'

useHead({
  title: 'Provenance — Essenfont',
  meta: [
    { name: 'description', content: 'Which donor font contributed each glyph? Per-codepoint provenance explorer.' },
  ],
  link: [{ rel: 'canonical', href: 'https://essenfont.github.io/provenance' }],
})

type ProvenanceBlock = {
  id: string
  first_cp: string
  last_cp: string
  primary_donor: string | null
  donors: string[]
  donor_counts: Record<string, number>
  codepoint_count: number
}

type ProvenanceData = {
  essenfont_version: string
  ucd_version: string
  generated_at: string
  donor_count: number
  codepoint_count: number
  donors: Record<string, { family: string; license: string; url?: string }>
  blocks: Record<string, ProvenanceBlock>
}

const data = ref<ProvenanceData | null>(null)
const filterDonor = ref<string>('')

// useBuildJson handles the SSR-vs-client fetch centrally.
const { useBuildJson } = await import('../composables/useBuildJson')
data.value = (await useBuildJson<ProvenanceData>('provenance.json')).value

const blocks = computed(() => {
  if (!data.value) return []
  const arr = Object.entries(data.value.blocks).map(([id, b]) => ({ id, ...b }))
  if (filterDonor.value) {
    return arr.filter(b => b.primary_donor === filterDonor.value)
  }
  return arr
})

const topDonors = computed(() => {
  if (!data.value) return []
  return Object.entries(data.value.donors)
    .map(([key, d]) => ({ key, ...d }))
    .slice(0, 12)
})
</script>

<template>
  <div class="catalog">
    <header class="catalog-masthead">
      <RouterLink to="/" class="back-mark">← Home</RouterLink>
      <div class="catalog-flag">
        <span class="flag-num">№ 06</span>
        <span class="flag-sep">·</span>
        <span class="flag-label">Provenance explorer</span>
      </div>
      <h1 class="catalog-title">Which donor font contributed each glyph?</h1>
      <p class="catalog-deck">
        Every glyph in essenfont is vector-extracted from a canonical OFL-licensed
        donor font. This is the per-block attribution map.
      </p>
    </header>

    <section v-if="data" class="overview">
      <div class="ov-cell"><span class="ov-num">{{ data.donor_count }}</span><span class="ov-lab">donors</span></div>
      <div class="ov-cell"><span class="ov-num">{{ data.codepoint_count.toLocaleString() }}</span><span class="ov-lab">codepoints traced</span></div>
      <div class="ov-cell"><span class="ov-num">{{ Object.keys(data.blocks).length }}</span><span class="ov-lab">blocks</span></div>
      <div class="ov-cell"><span class="ov-num">{{ data.ucd_version }}</span><span class="ov-lab">Unicode version</span></div>
    </section>

    <section v-if="topDonors.length" class="donor-filter">
      <span class="filter-label">Filter by primary donor:</span>
      <button class="filter-pill" :class="{ active: !filterDonor }" @click="filterDonor = ''">All</button>
      <button
        v-for="d in topDonors"
        :key="d.key"
        class="filter-pill"
        :class="{ active: filterDonor === d.key }"
        @click="filterDonor = d.key"
      >
        {{ d.family }}
      </button>
    </section>

    <section v-if="data" class="block-table-wrap">
      <table class="block-table">
        <thead>
          <tr>
            <th>Block</th>
            <th>Range</th>
            <th>Codepoints</th>
            <th>Primary donor</th>
            <th>Contributors</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="b in blocks" :key="b.id" :class="{ dim: filterDonor && b.primary_donor !== filterDonor }">
            <td><RouterLink :to="`/unicode/block/${b.id.toLowerCase().replace(/_/g, '-')}`" class="block-link">{{ b.id.replace(/_/g, ' ') }}</RouterLink></td>
            <td><code>{{ b.first_cp }}–{{ b.last_cp }}</code></td>
            <td>{{ b.codepoint_count.toLocaleString() }}</td>
            <td>
              <RouterLink v-if="b.primary_donor" :to="`/donors/${b.primary_donor.toLowerCase().replace(/_/g, '-')}`" class="donor-link">{{ data.donors[b.primary_donor]?.family ?? b.primary_donor }}</RouterLink>
              <span v-else class="dim">—</span>
            </td>
            <td>{{ b.donors.length }}</td>
          </tr>
        </tbody>
      </table>
    </section>

    <section v-else class="empty">
      <p>Provenance data not available yet. It's generated by <code>scripts/emit_provenance.rb</code> at release time and uploaded to the GH Release.</p>
      <p>Once a release ships with provenance data, this page populates automatically.</p>
    </section>
  </div>
</template>

<style scoped>
.catalog { max-width: 1080px; margin: 0 auto; padding: 4rem 2rem 6rem; color: var(--spec-ink); }
.catalog-masthead { margin-bottom: 3rem; }
.back-mark {
  font-family: var(--spec-font-mono); font-size: 0.74rem; letter-spacing: 0.08em;
  color: var(--spec-rose); text-decoration: none; text-transform: uppercase;
}
.back-mark:hover { text-decoration: underline; }
.catalog-flag {
  display: flex; align-items: baseline; gap: 0.7rem;
  margin: 2rem 0 1.2rem;
  font-family: var(--spec-font-mono); font-size: 0.72rem; letter-spacing: 0.18em;
  text-transform: uppercase; color: var(--spec-ink-soft);
}
.flag-num { color: var(--spec-rose); font-weight: 600; }
.flag-sep { opacity: 0.4; }
.catalog-title {
  font-family: var(--spec-font-display);
  font-size: clamp(1.8rem, 4vw, 2.6rem); font-weight: 300;
  line-height: 1.1; letter-spacing: -0.025em; margin: 0 0 1rem;
}
.catalog-deck {
  font-family: var(--spec-font-display); font-size: 1.05rem; font-weight: 300;
  line-height: 1.55; max-width: 60ch; margin: 0; color: var(--spec-ink-soft);
}

.overview { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 2rem; padding: 1.5rem 0; border-top: 1px solid var(--spec-rule); border-bottom: 1px solid var(--spec-rule); }
@media (max-width: 720px) { .overview { grid-template-columns: repeat(2, 1fr); } }
.ov-cell { display: flex; flex-direction: column; gap: 0.3rem; }
.ov-num { font-family: var(--spec-font-display); font-size: 1.8rem; font-weight: 300; color: var(--spec-ink); line-height: 1; }
.ov-lab { font-family: var(--spec-font-mono); font-size: 0.66rem; letter-spacing: 0.1em; text-transform: uppercase; color: var(--spec-ink-soft); opacity: 0.7; }

.donor-filter { display: flex; flex-wrap: wrap; gap: 0.4rem; align-items: center; margin-bottom: 2rem; }
.filter-label { font-family: var(--spec-font-mono); font-size: 0.68rem; letter-spacing: 0.1em; text-transform: uppercase; color: var(--spec-ink-soft); margin-right: 0.5rem; }
.filter-pill {
  font-family: var(--spec-font-mono); font-size: 0.7rem;
  padding: 0.25rem 0.65rem; border: 1px solid var(--spec-rule); border-radius: 999px;
  background: transparent; color: var(--spec-ink-soft); cursor: pointer;
  transition: all 0.15s;
}
.filter-pill:hover { border-color: var(--spec-rose); color: var(--spec-rose); }
.filter-pill.active { background: var(--spec-rose); color: #fff; border-color: var(--spec-rose); }

.block-table-wrap { overflow-x: auto; }
.block-table { width: 100%; border-collapse: collapse; font-family: var(--spec-font-mono); font-size: 0.82rem; }
.block-table th { text-align: left; padding: 0.7rem 0.8rem; font-size: 0.66rem; letter-spacing: 0.12em; text-transform: uppercase; color: var(--spec-ink-soft); border-bottom: 1px solid var(--spec-rule-strong); }
.block-table td { padding: 0.7rem 0.8rem; border-bottom: 1px solid var(--spec-rule); color: var(--spec-ink); }
.block-table tr:hover td { background: rgba(184, 71, 95, 0.04); }
.block-table tr.dim td { opacity: 0.4; }
.block-table td code { font-size: 0.78rem; color: var(--spec-ink-soft); }
.block-link, .donor-link { color: var(--spec-rose); text-decoration: none; }
.block-link:hover, .donor-link:hover { text-decoration: underline; }

.empty { padding: 3rem 0; text-align: center; font-family: var(--spec-font-display); color: var(--spec-ink-soft); }
.empty code { font-family: var(--spec-font-mono); font-size: 0.85rem; color: var(--spec-rose); }
</style>
